package utils

import game.dune_map._
import game.sector._

object TerritorySectors {

  val aSectorOnTerritory: Map[Territory, Sector] = Map(
    Meridan -> Sector0,
    CielagoSouth -> Sector1,
    CielagoEast -> Sector2,
    SouthMesa -> Sector3,
    RedChasm -> Sector6,
    GaraKulon -> Sector7,
    SihayaRidge -> Sector8,
    Basin -> Sector8,
    OldGap -> Sector8,
    Arsunt -> Sector10,
    HaggaBasin -> Sector11,
    WindPassNorth -> Sector16,
    HargPass -> Sector3,
    WindPass -> Sector13,
    CielagoWest -> Sector17,
    CielagoDepression -> Sector0,
    CielagoNorth -> Sector0,
    TheMinorErg -> Sector4,
    HoleInTheRock -> Sector8,
    Tsimpo -> Sector10,
    ImperialBasin -> Sector8,
    BrokenLand -> Sector10,
    RockOutcroppings -> Sector12,
    BlightOfTheCliff -> Sector13,
    FuneralPlains -> Sector14,
    TheGreaterFlat -> Sector15,
    TheGreatFlat -> Sector14,
    HabbanyaErg -> Sector15,
    HabbanyaRidgeFlat -> Sector16,
    TueksSietch -> Sector4,
    Arrakeen -> Sector9,
    Carthag -> Sector10,
    SietchTabr -> Sector13,
    HabbanyaRidgeSietch -> Sector16,
    FalseWallSouth -> Sector3,
    PastyMesa -> Sector4,
    ShieldWall -> Sector7,
    RimWallWest -> Sector8,
    PlasticBasin -> Sector11,
    FalseWallWest -> Sector15,
    FalseWallEast -> Sector4,
    PolarSink -> FakePolarSector,
  )

  val duneSectorsInTerritorySurrounding: Map[Territory, Set[Sector]] = Map(
    Meridan -> Set(Sector17, Sector0, Sector1),
    CielagoSouth -> Set(Sector1, Sector2),
    CielagoEast -> Set(Sector2, Sector3),
    SouthMesa -> Set(Sector3, Sector4, Sector5, Sector6),
    RedChasm -> Set(Sector5, Sector6),
    GaraKulon -> Set(Sector7, Sector8),
    SihayaRidge -> Set(Sector7, Sector8),
    Basin -> Set(Sector8),
    OldGap -> Set(Sector8, Sector9, Sector10),
    Arsunt -> Set(Sector10, Sector11, FakePolarSector),
    HaggaBasin -> Set(Sector10, Sector11, Sector12, Sector13, FakePolarSector),
    WindPassNorth -> Set(Sector16, Sector17, Sector0, FakePolarSector),
    HargPass -> Set(Sector2, Sector3, Sector4, FakePolarSector),
    WindPass -> Set(Sector12, Sector13, Sector14, Sector15, Sector16, Sector17, FakePolarSector),
    CielagoWest -> Set(Sector16, Sector17, Sector0),
    CielagoDepression -> Set(Sector0, Sector1, Sector2),
    CielagoNorth -> Set(Sector17, Sector0, Sector1, Sector2, Sector3, FakePolarSector),
    TheMinorErg -> Set(Sector4, Sector5, Sector6, Sector7),
    HoleInTheRock -> Set(Sector8),
    Tsimpo -> Set(Sector9, Sector10, Sector11),
    ImperialBasin -> Set(Sector8, Sector9, Sector10, FakePolarSector),
    BrokenLand -> Set(Sector9, Sector10, Sector11),
    RockOutcroppings -> Set(Sector10, Sector11, Sector12),
    BlightOfTheCliff -> Set(Sector12, Sector13),
    FuneralPlains -> Set(Sector12, Sector13),
    TheGreaterFlat -> Set(Sector12, Sector13, Sector14),
    TheGreatFlat -> Set(Sector13, Sector14),
    HabbanyaErg -> Set(Sector15, Sector16),
    HabbanyaRidgeFlat -> Set(Sector15, Sector16, Sector17, Sector0),
    TueksSietch -> Set(Sector4),
    Arrakeen -> Set(Sector8, Sector9),
    Carthag -> Set(Sector9, Sector10),
    SietchTabr -> Set(Sector13),
    HabbanyaRidgeSietch -> Set(Sector16),
    FalseWallSouth -> Set(Sector2, Sector3, Sector4),
    PastyMesa -> Set(Sector4, Sector5, Sector6, Sector7),
    ShieldWall -> Set(Sector7, Sector8),
    RimWallWest -> Set(Sector8, Sector9),
    PlasticBasin -> Set(Sector10, Sector11, Sector12, Sector13, Sector14),
    FalseWallWest -> Set(Sector15, Sector16, Sector17),
    FalseWallEast -> Set(Sector4, Sector5, Sector6, Sector7, Sector8, FakePolarSector),
    PolarSink -> Set(FakePolarSector)
  )
}
